version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
      target: installer
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: bash -c "yarn install --immutable && yarn start"
